local d04 = require "d04"
local util = require "util"

describe("day 4", function ()
  describe("part a", function ()
    it("we can find if one range fully contains the other in an assignment pair", function ()
      assert.are.equal(false, d04.has_full_overlap("2-6,4-8")) 
      assert.are.equal(true, d04.has_full_overlap("2-8,3-7")) 
      assert.are.equal(true, d04.has_full_overlap("6-6,4-6")) 
    end)
    it("we can find the number of assignment pairs where one range fully contains the other", function ()
      local input = util.lines_from_file("d04a_test.txt")
      assert.are.equal(2, d04.count_of_overlaps(input, true))
    end)
    it("with actual input", function ()
      local input = util.lines_from_file("d04_input.txt")
      assert.are.equal(550, d04.count_of_overlaps(input, true))
    end)
  end)
  describe("part b", function ()
    it("we can find if there is any overlap in an assignment pair", function ()
      assert.are.equal(true, d04.has_overlap("2-6,4-8")) 
      assert.are.equal(true, d04.has_overlap("2-8,3-7")) 
      assert.are.equal(true, d04.has_overlap("6-6,4-6")) 
      assert.are.equal(false, d04.has_overlap("2-3,4-5")) 
    end)
    it("we can find the number of assignment pairs where there is an overlap", function ()
      local input = util.lines_from_file("d04a_test.txt")
      assert.are.equal(4, d04.count_of_overlaps(input))
    end)
    it("with actual input", function ()
      local input = util.lines_from_file("d04_input.txt")
      assert.are.equal(931, d04.count_of_overlaps(input))
    end)
  end)
end)

