local util = require "util"
local d15 = require "d15"

local Point = d15.Point

describe("day 15", function ()
  local test_input = util.lines_from_file("d15a_test.txt")
  local real_input = util.lines_from_file("d15_input.txt")
  describe("part a", function ()
    it("can deploy sensors", function ()
      local sensors = d15.deploy_sensors(test_input)
      assert.is.equal(14, #sensors)
      _, rx = sensors:xrange(11)
      assert.is.equal(26, rx)
    end)
    it("with actual input", function ()
      local sensors = d15.deploy_sensors(real_input)
      _, rx = sensors:xrange(2000000)
      assert.is.equal(4502208, rx)
    end)
  end)
  describe("part b", function ()
    it("with test input", function ()
      local sensors = d15.deploy_sensors(test_input)
      local dloc = sensors:find_distress_loc(20, 20)
      assert.is.equal(Point(14, 11), dloc)
    end)
    it("with actual input", function ()
      local sensors = d15.deploy_sensors(real_input)
      local dloc = sensors:find_distress_loc(4000000, 4000000)
      assert.is.equal(13784551204480, dloc.x*4000000 + dloc.y)
    end)
  end)
end)